### ISSUE TITLE
Upgrade gradle version

### ISSUE THREAD

**Issue by Vlad-Adrian** [littleGnAl/http_proxy_override#4]
Hello 👋,

Are there any plans in upgrading the gradle version? It is currently blocking the upgrade of some other packages.

I would be more than happy to help with this.

Thanks!

**Comment by littleGnAl** [comment]
Thanks, @ Vlad-Adrian, I may not have time to follow up on this issue, feel free to open PR and welcome!

**Comment by Vlad-Adrian** [comment]
Hi @littleGnAl, I raised a PR for this issue. Can you please check it when you have some time.

Thanks!

**Comment by littleGnAl** [comment]
The 1.0.1 with the upgrade was published to pub.dev
https://pub.dev/packages/http_proxy_override/versions/1.0.1
